version: '3'

services:

    snappass:
        image: snappass_sebnet
        ports:
            - "5000:5000"
        stop_signal: SIGINT
        environment:
            - REDIS_HOST=redis
            - NO_SSL=True
            - STATIC_URL=/static
            - LISTEN_IP=0.0.0.0
        depends_on:
          - redis

    redis:
        image: "redis:latest"
